<?php
    $printedBy = $printedBy ?? null;
    $printedAt = $printedAt ?? null;
    $companyName = \App\Services\SettingsService::get('app_name', 'SewaJas');
    $companyEmail = \App\Services\SettingsService::get('company_email', 'support@sewajas.id');
    $companyWebsite = \App\Services\SettingsService::get('company_website', 'www.sewajas.id');
    $appName = \App\Services\SettingsService::get('app_name', 'SewaJas');
?>
<div class="doc-footer">
    <div style="font-weight:700; color:#111827; margin-bottom:6px; font-size:12px; letter-spacing:0.02em;">Thank You</div>
    <div style="margin-bottom:6px; color:#64748B; line-height:1.6;">Need Help?</div>
    <div style="margin-bottom:4px; color:#64748B; line-height:1.5;"><?php echo e($companyEmail); ?></div>
    <div style="margin-bottom:4px; color:#64748B; line-height:1.5;"><?php echo e($companyWebsite); ?></div>
    <?php if(!empty($printedBy)): ?>
    <div style="margin-top:4px; font-size:10px; color:#64748B; line-height:1.5;">
        Dicetak oleh: <?php echo e($printedBy); ?> · <?php echo e($printedAt); ?>

    </div>
    <?php endif; ?>
    <div style="margin-top:8px; font-size:9px; color:#94A3B8; line-height:1.5;">
        Auto generated by <?php echo e($companyName); ?> System. Tidak memerlukan tanda tangan.<br>
        Powered by <?php echo e($appName); ?> ERP v1.0
    </div>
</div>
<?php /**PATH C:\xampp82\htdocs\rental-jas-main\resources\views/rentals/partials/doc-premium-footer.blade.php ENDPATH**/ ?>