@php
    $rental = $rental ?? null;
    $receiptNumber = 'RCPT-' . ($rental->invoice_number ?? '-');
@endphp

<div class="audit-card">
    <div class="audit-card-title">Audit Trail</div>
    <table style="width:100%; border-collapse:collapse;">
        <tr>
            <td style="width:50%; vertical-align:top; padding-right:10px; border-right:1px solid #E5E7EB;">
                <div class="audit-row">
                    <span class="audit-label">Receipt</span>
                    <span class="audit-value" style="background:#EFF6FF; color:#1E40AF; padding:6px 14px; border-radius:999px; font-size:11px; font-weight:700; display:inline-block; border:1px solid #E5E7EB;">{{ $receiptNumber }}</span>
                </div>
            </td>
            <td style="width:50%; vertical-align:top; padding-left:10px;">
                <div class="audit-row">
                    <span class="audit-label">Generated At</span>
                    <span class="audit-value">{{ optional($rental->created_at)->format('d M Y H:i') ?? '-' }}</span>
                </div>
                <div class="audit-row">
                    <span class="audit-label">Generated By</span>
                    <span class="audit-value">{{ optional($rental->createdBy)->name ?? \App\Services\SettingsService::get('app_name', 'SewaJas') }}</span>
                </div>
                <div class="audit-row">
                    <span class="audit-label">Verified</span>
                    <span class="audit-value" style="background:#DCFCE7; color:#15803D; padding:6px 14px; border-radius:999px; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:0.06em; display:inline-block;">VERIFIED</span>
                </div>
            </td>
        </tr>
    </table>
</div>
