@php
    $printedBy = $printedBy ?? null;
    $printedAt = $printedAt ?? null;
@endphp
<div class="doc-footer">
    <div style="font-weight:700; color:#111827; margin-bottom:6px; font-size:12px; letter-spacing:0.02em;">Thank You</div>
    <div style="margin-bottom:6px; color:#64748B; line-height:1.6;">Need Help?</div>
    <div style="margin-bottom:4px; color:#64748B; line-height:1.5;">support@sewajas.id</div>
    <div style="margin-bottom:4px; color:#64748B; line-height:1.5;">www.sewajas.id</div>
    @if(!empty($printedBy))
    <div style="margin-top:4px; font-size:10px; color:#64748B; line-height:1.5;">
        Dicetak oleh: {{ $printedBy }} · {{ $printedAt }}
    </div>
    @endif
    <div style="margin-top:8px; font-size:9px; color:#94A3B8; line-height:1.5;">
        Auto generated by SewaJas System. Tidak memerlukan tanda tangan.<br>
        Powered by SewaJas ERP v1.0
    </div>
</div>
